### ISSUE TITLE
Where is the trained models?

### ISSUE THREAD

**Issue by szxiangjn** [parajain/structscribe#2]
Hi, I am trying to run your codes, but it throws the error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data1/struct2text/s2s_one_models/model_softmax_1_acc_96.73_ppl_1.67_e5.pt'
```
Seems that we don't have the models. Where can I download it?

Thanks in advance!

**Comment by parajain** [comment]
Hi,

Sorry for delay in response.

We do not have the demo or models online now. But that is a simple seq2eq model which was trained using OpenNMT platform, I am afraid but these will have to be trained again now.

Thanks
